### ISSUE TITLE
Questionable task description "Shaky day"

### ISSUE THREAD

**Issue by Acefall** [data-hydenv/hydenv-database#18]
In Exercise Earthquakes/Shaky Day/ it says "Check out the correct casting function in the Postgres documentation." However, in the solution there is no casting function.

**Comment by mmaelicke** [comment]
I'll have a look asap

**Comment by mmaelicke** [comment]
In a strict sense, there is actually a casting function here: 

The first part of the solution looks like:
```SQL
SELECT datum, count(*), array_agg(magnitude) AS magnitudes FROM earthquakes
```

Here, the `array_agg` will turn a number of magnitude values (data type: `real`) to an array of data type `real[]`. In a strict sense, this is another data type. Nevertheless, I updated the description to be more clear on this. The updated exercises should go live at some point today.
