### ISSUE TITLE
Loading data multiple times

### ISSUE THREAD

**Issue by JL-Rosien** [data-hydenv/hydenv-database#25]
It is possible to load data tables multiple times in the hydenv - database, resulting in error messenges with some codes since  he finds same information twice. 
For example: 

`SELECT *, value AS temp_lux  FROM raw_data 
WHERE meta_id =
(SELECT DISTINCT id from metadata WHERE device_id = 'YOUR HOBO NUMBER' and term_id=11)
`
--> Error: "more than one row" 

CLeaning the database again with `python -m hydenv database init --clean` and installing and loading everything again was the solution for me. 
*Note: All your established "Views" and "tables" will get lost when doing so!

**Comment by mmaelicke** [comment]
Thanks for reporting!
I think this is something that can be fixed quite quickly. I think.

**Comment by mmaelicke** [comment]
This behavior has been fixed with Version `0.9.1`.
Now, the CLI should abort if the metadata is already in the database.
