### ISSUE TITLE
Spelling mistake in the hydenv GUI module

### ISSUE THREAD

**Issue by jasperschalla** [data-hydenv/hydenv-database#34]
There is a spelling mistake in the parameter "skip_init" in the hydenv-database/hydenv/gui/main.py script. The parameter is rather called "skipt_init" there. The mentioned line of code can be found here: https://github.com/data-hydenv/hydenv-database/blob/a266024bdffc831076ed4855c842735f5c763aa0/hydenv/gui/main.py#L391

**Comment by mmaelicke** [comment]
Thanks for pointing out and delivering the solution! 

Fix in commit https://github.com/data-hydenv/hydenv-database/commit/0935faab28f366d9a0eb69a98d629083e09943f1

New version `0.9.17` just pushed, can be updated using `pip install --upgrade hydenv`
