### ISSUE TITLE
--terms=[WT18,WT19,WT20,WT21,WT22] on Mac does not upload

### ISSUE THREAD

**Issue by jakecreynolds** [data-hydenv/hydenv-database#35]
"python -m hydenv examples hobo --terms=[WT18,WT19,WT20,WT21,WT22] –-only=metadata" command does not upload the data on mac. 

formatted as: "python -m hydenv examples hobo --terms=WT22 --only=metadata" able to upload terms 1 by 1

**Comment by mmaelicke** [comment]
Thanks for reporting, would you mind reporting your OS version?

**Comment by jakecreynolds** [comment]
Version 11.6.1

**Comment by mmaelicke** [comment]
Do you remember if we checked that there is no whitespace between the arguments inside the list?

So `--terms=[WT18, WT19]` is **not** supposed to work, but `--terms=[WT18,WT19]` should. However, for you both don't work, right?

**Comment by jakecreynolds** [comment]
Correct, both don't work.

python -m hydenv examples hobo --terms=[WT18,WT19,WT20,WT21] –-only=metadata 
zsh: no matches found: --terms=[WT18,WT19,WT20,WT21]

**Comment by mmaelicke** [comment]
all right, thanks. I will look into this

**Comment by mmaelicke** [comment]
I finally found the solution while preparing for this year. On Mac, the `[ ... ]` try string interpolation, thus you need to quote this:

`--terms="[WT19,WT20]"`
