### ISSUE TITLE
Exercises Application start 404

### ISSUE THREAD

**Issue by Acefall** [data-hydenv/hydenv-database#6]
When starting the exercises application the index.html is not found.
Sadly there is not much more information why it is not working. Maybe the port is already in use? Can I specify a different port for the exercises app?

Error Message below:
```
(base) alex@alex-H97-D3H:~$ python -m hydenv exercises start
http://localhost:5000/
http://localhost:5000/
Starting backend server: http://localhost:5000/
Backend is running.
 * Serving Flask app "backend" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 972-262-065
127.0.0.1 - - [10/Jan/2021 16:44:18] "GET /index.html HTTP/1.1" 404 -
```

**Comment by mmaelicke** [comment]
Thanks for reporting. I could just reproduce the problem and will try to understand it. Will respond asap.
The port is not the problem...

**Comment by mmaelicke** [comment]
I might have fixed it. Can you install `hydenv>=0.8.4`, either by a new install or by `pip install --upgrade hydenv`?

Sorry for the inconvenience, you're the first user...

**Comment by Acefall** [comment]
It works!
No Problem. It happened to me before. Everything running smoothly and as soon as someone else tries to use the software it breaks.
