### ISSUE TITLE
No Textinput for Queries

### ISSUE THREAD

**Issue by Acefall** [data-hydenv/hydenv-database#7]
After starting the first lesson in the earthquake  "Getting started" exercise I cannot find the text area to input my query. I have a light blue bar over a darker blue background that I can move up and down. Presumably that is the resizing bar. See image.
![earthquake](https://user-images.githubusercontent.com/76061447/104130407-e5191180-5370-11eb-9a8f-0c21dea1a8d8.png)

**Comment by mmaelicke** [comment]
Thanks, I spotted the problem and started fixing. These kind of errors don't happen on my development environment and I missed them in the (sparse) tests. 
I try to fix it asap.

**Comment by mmaelicke** [comment]
There is `hydenv 0.8.5` now. The package has doubled it's size, as there was some stuff that got lost during packaging. Hope this fixes the issue... I can't test here right now. If it's not fixed, I will look into it tomorrow.
Thanks!

**Comment by Acefall** [comment]
It works now.
