### ISSUE TITLE
Magnitude range sample solution is incorrect

### ISSUE THREAD

**Issue by Acefall** [data-hydenv/hydenv-database#9]
In the "Magnitude Range" exercise is the sample solution marked as incorrect when it is executed.

**Comment by mmaelicke** [comment]
That's true. I have no idea why, right now. Happens on a number of exercises right now, that used to work fine in the past. I'll have to dig into this...

**Comment by mmaelicke** [comment]
A classic, embarassing floating-point comparator issue, like:

`0.1 + 0.2 !== 0.3`

I think with `hydenv 0.8.7` a number of these false feedbacks are fixed now, but I expect that more similar problems might come up.

We can keep this issue open for some time, to see if more / similar issues arise.

**Comment by mmaelicke** [comment]
I checked ~10 exercises that didn't work and all of them are working now, therefore I'll close the issue. If any similar problem is arising, this issue can be re-opened, or a new one can be opened.
